TAGS_DS_FIELD_ID_COLUMN_LABEL = 'field_id'
TAGS_DS_FIELD_VALUE_COLUMN_LABEL = 'field_value'
TAGS_DS_LINKED_RESOURCE_ENTRY_NAME_COLUMN_LABEL = 'linked_resource OR entry_name'
TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL = 'column'
TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL = 'template_name'

TAGS_DS_COLUMNS_ORDER = (TAGS_DS_LINKED_RESOURCE_ENTRY_NAME_COLUMN_LABEL,
                         TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL, TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL,
                         TAGS_DS_FIELD_ID_COLUMN_LABEL, TAGS_DS_FIELD_VALUE_COLUMN_LABEL)

TAGS_DS_FILLABLE_COLUMNS = [
    TAGS_DS_LINKED_RESOURCE_ENTRY_NAME_COLUMN_LABEL, TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL
]

TAGS_DS_NON_FILLABLE_COLUMNS = [
    TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL, TAGS_DS_FIELD_ID_COLUMN_LABEL,
    TAGS_DS_FIELD_VALUE_COLUMN_LABEL
]

BIGQUERY_LINKED_RESOURCE_PATTERN = '^//bigquery.googleapis.com/(?P<resource_name>.+?)$'
PUBSUB_LINKED_RESOURCE_PATTERN = '^//pubsub.googleapis.com/(?P<resource_name>.+?)$'
