TAG_DS_FIELD_ID_COLUMN_LABEL = 'field_id'
TAG_DS_FIELD_VALUE_COLUMN_LABEL = 'field_value'
TAG_DS_LINKED_RESOURCE_COLUMN_LABEL = 'linked_resource'
TAG_DS_SCHEMA_COLUMN_COLUMN_LABEL = 'column'
TAG_DS_TEMPLATE_NAME_COLUMN_LABEL = 'template_name'

TAG_DS_COLUMNS_ORDER = (
    TAG_DS_LINKED_RESOURCE_COLUMN_LABEL,
    TAG_DS_TEMPLATE_NAME_COLUMN_LABEL,
    TAG_DS_SCHEMA_COLUMN_COLUMN_LABEL,
    TAG_DS_FIELD_ID_COLUMN_LABEL,
    TAG_DS_FIELD_VALUE_COLUMN_LABEL
)

TAG_DS_FILLABLE_COLUMNS = [
    TAG_DS_LINKED_RESOURCE_COLUMN_LABEL,
    TAG_DS_TEMPLATE_NAME_COLUMN_LABEL
]

TAG_DS_NON_FILLABLE_COLUMNS = [
    TAG_DS_SCHEMA_COLUMN_COLUMN_LABEL,
    TAG_DS_FIELD_ID_COLUMN_LABEL,
    TAG_DS_FIELD_VALUE_COLUMN_LABEL
]
