TAGS_DS_FIELD_ID_COLUMN_LABEL = 'field_id'
TAGS_DS_FIELD_VALUE_COLUMN_LABEL = 'field_value'
TAGS_DS_LINKED_RESOURCE_COLUMN_LABEL = 'linked_resource'
TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL = 'column'
TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL = 'template_name'

TAGS_DS_COLUMNS_ORDER = (TAGS_DS_LINKED_RESOURCE_COLUMN_LABEL, TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL,
                         TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL, TAGS_DS_FIELD_ID_COLUMN_LABEL,
                         TAGS_DS_FIELD_VALUE_COLUMN_LABEL)

TAGS_DS_FILLABLE_COLUMNS = [
    TAGS_DS_LINKED_RESOURCE_COLUMN_LABEL, TAGS_DS_TEMPLATE_NAME_COLUMN_LABEL
]

TAGS_DS_NON_FILLABLE_COLUMNS = [
    TAGS_DS_SCHEMA_COLUMN_COLUMN_LABEL, TAGS_DS_FIELD_ID_COLUMN_LABEL,
    TAGS_DS_FIELD_VALUE_COLUMN_LABEL
]
